# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(default='z', max_length=1),
        ),
    ]
