# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0002_question_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NYRP.Group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NYRP.Hint'),
        ),
    ]
