# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0003_auto_20170626_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bug_rep',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='diagram',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
