# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0006_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selector',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NYRP.Question'),
        ),
    ]
