# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0007_auto_20170827_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selector',
            name='questions',
        ),
        migrations.AddField(
            model_name='selector',
            name='questions',
            field=models.ManyToManyField(to='NYRP.Question'),
        ),
    ]
