# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0008_auto_20170827_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='choice_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='selector',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selector',
            name='record',
            field=models.TextField(default=''),
        ),
    ]
