# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0012_auto_20170914_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
