# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0015_auto_20170914_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='indexes',
            field=models.CharField(default='[', max_length=1000),
        ),
    ]
