# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0016_selector_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='indexes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
