# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0018_auto_20170919_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_choices', models.CharField(choices=[('1', "This question doesn't belong in this topic."), ('2', "This question doesn't belong in this unit."), ('3', 'The given answer is incorrect.'), ('4', 'There is a formatting/typo error in the question.'), ('5', 'Other (please specify below).')], default='5', max_length=1)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NYRP.Question')),
            ],
        ),
    ]
