# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0019_questionbug'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='subject',
            field=models.CharField(default='ERRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbug',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbug',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
