# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0020_auto_20170927_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('CHEM', 'Chemistry'), ('USHG', 'US History And Government'), ('ALG1', 'Algebra I'), ('ALG2', 'Algebra II Common Core'), ('GHGE', 'Global History And Geography'), ('PHYS', 'Physics'), ('ERRO', 'Error: no subject')], default='ERRO', max_length=4),
        ),
    ]
