# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0021_auto_20170927_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bug_rep',
        ),
    ]
