# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0022_remove_question_bug_rep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='dhint3',
            new_name='name',
        ),
    ]
