# Generated by Django 3.1.5 on 2024-11-10 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0023_auto_20170929_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('new_feature_requests', models.JSONField(default=list)),
                ('misc_feedback', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='selector',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NYRP.group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NYRP.hint'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('CHEM', 'Chemistry'), ('USHG', 'US History And Government'), ('ALG1', 'Algebra I'), ('ALG2', 'Algebra II Common Core'), ('GHG2', 'Global History And Geography II'), ('PHYS', 'Physics'), ('ESCI', 'Earth Science'), ('GEOM', 'Geometry'), ('LIVE', 'Living Environment'), ('ERRO', 'Error: no subject')], default='ERRO', max_length=4),
        ),
    ]
