# Generated by Django 3.1.5 on 2024-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYRP', '0024_auto_20241110_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='new_feature_requests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
